# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37e9428bd2d1f054e003bf7979207084bc3a95eb73df879e13c794f9fd37ad1c23a48ec355f28a4d15d387f352ef7c2129dcbd4cff92f9e8dbfe67cf56668b8d

test:
  secret_key_base: b9a045c0df54640b3e2a91148dbb24d93604b9050e0071c99a159713b1a13a41292c881bbedf3bca649d8e6ddc940ffdf641999ab344626090797a1a7c643a0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
